# Generated by Django 4.1.5 on 2023-01-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
